### ISSUE TITLE
Disable cursor shift

### ISSUE THREAD

**Issue by nichollascarter** [adafruit/Adafruit_Python_CharLCD#24]
Hello! Please, help me with a some question. I need to disable cursor moving when using function 
lcd.message(). If I use lcd.set_cursor() and after this use lcd.message(), cursor changes his position.
How I can disable this effect?

**Comment by kattni** [comment]
Hello. We're going to be deprecating this library in favor of this one: https://github.com/adafruit/Adafruit_CircuitPython_CharLCD

I have filed an issue on that repo for this feature request. https://github.com/adafruit/Adafruit_CircuitPython_CharLCD/issues/21

As it is, `message` resets to the beginning of the line. This is by design. We will need to add a new feature to allow the cursor to remain where you set it with `cursor_position` when you call `message`.

That library is available on PyPI for you to `pip3 install adafruit-circuitpython-charlcd` and use on Raspberry Pi thanks to the Adafruit-Blinka library which should install automatically along with the other dependencies needed for using `charlcd`.  Please see the [documentation](https://circuitpython.readthedocs.io/projects/charlcd/en/latest/) for API and usage examples. There are Raspberry Pi-specific examples in the `examples/` folder in the repo.
