### ISSUE TITLE
Off-by-one error in set_cursor

### ISSUE THREAD

**Issue by ali1234** [adafruit/Adafruit_Python_CharLCD#27]
I believe this is an off-by-one-error:

https://github.com/adafruit/Adafruit_Python_CharLCD/blob/master/Adafruit_CharLCD/Adafruit_CharLCD.py#L177

Should be >= otherwise we can address rows 0, 1, or 2 on a 2 line display.

**Comment by kattni** [comment]
Hello, this issue is not present in a newer version of the library. It is designed to allow for addressing any number of rows, but if the number is larger than the number of lines, it defaults to the last line on the display.

We're going to be deprecating this library in favor of this one: https://github.com/adafruit/Adafruit_CircuitPython_CharLCD

That library is available on PyPI for you to `pip3 install adafruit-circuitpython-charlcd` and use on Raspberry Pi thanks to the Adafruit-Blinka library which should install automatically along with the other dependencies needed for using `charlcd`.  Please see the [documentation](https://circuitpython.readthedocs.io/projects/charlcd/en/latest/) for API and usage examples. There are Raspberry Pi-specific examples in the `examples/` folder in the repo.
